name : 'Default environment variables'

on:
    push:

jobs:
    mainjob:
        name: 'Print the default Github vars'
        runs-on: ubuntu-latest

        steps:
        - name: print-values-of-variables
          run:
            echo "$GITHUB_ACTION"
            echo "$GITHUB_ENV"
            echo "$GITHUB_JOB"
